### ISSUE TITLE
How to apply Hanning window to time series?

### ISSUE THREAD

**Issue by chrisdane** [gjmvanboxtel/gsignal#14]
Hi

Thanks a lot for the nice functions of the gsignal package. I have a question.

How can I apply the Hanning window `han <- gsignal::hanning(10)` to time series `x  <- rnorm(100)` to get a smoothed version of `x`?

Thanks a lot for help and kind regards,
Chris

**Comment by gjmvanboxtel** [comment]
Hi,

I am not sure what you are trying to achieve. Windowing functions such as Hanning are normally used for multiplying with the data prior to an FFT to avoid spectral leakage. In that case you will want to use a window of the same length as your data or data segment.

But the Hanning window does have low-pass properties so it could in principle be used for smoothing your data. You will want to normalize the window in that case, so the following code coud be used:

```
x <- rnorm(100)
han <- gsignal::hanning(10)
han <- han/sum(han)
plot(x, type="l")
filt <- gsignal::conv(x, han, "same")
lines(filt, col="red")

```

Hope this helps.
Best,
Geert
