### ISSUE TITLE
Incorrect result / error exit in residuez()

### ISSUE THREAD

**Issue by loeriver** [gjmvanboxtel/gsignal#15]
For 2 "special" cases of inputs `residuez()` fails:

1) In case of a complex FIR part in the result, the returned value is conjugate w.r.t. the true value: 

`rv<-residuez(c(1+3i,-3i),c(1,-1))` 
> rv
$r
[1] 1

>$p
[1] 1

>$k
[1] 0-3i

The true result for `rv$k` in this case is `0+3i`: manual calculation and Python's scipy.signal.residuez show this. This bug is inherited from Octave, which gives the same wrong result. Remedy would be to leave out `Conj` in line 70 of the source.

2) If the result would consist of an FIR part only, `residuez()` fails w/ the error message `wrong sign in 'by' argument`, caused by the call to `mpoles(p)` for an empty p:

`rv2<-residuez(3,2)`
`Fehler in seq.default(np, 1, -1) : falsches Vorzeichen im 'by' Argument`

The call to `mpoles(p)` should be made conditional. Octave returns a correct result here (as does Python).

**Comment by gjmvanboxtel** [comment]
Thank you very much for your contribution, loeriver!

The changes were made in a new commit just now, so the issues are resolved if you install the latest version from Github. I will push then to CRAN somewhere in the fall.

Thanks again!
Geert
