### ISSUE TITLE
findpeaks gives a cryptic error:  'names' attribute [2] must be the same length as the vector [0]

### ISSUE THREAD

**Issue by bnicenboim** [gjmvanboxtel/gsignal#22]
`findpeaks` is not working with this vector of data: [problem.zip](https://github.com/user-attachments/files/16799508/problem.zip)

```r 
gsignal::findpeaks(data = problem, MinPeakDistance = 100)
# Error in names(x) <- value : 
#  'names' attribute [2] must be the same length as the vector [0]
```

(I also tried with the newest version gsignal_0.3-6.9010)

**Comment by gjmvanboxtel** [comment]
Thanks, this was also fixed in v0.3-7.9000. It was a typo in the code.
