### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by dipterix** [gjmvanboxtel/gsignal#23]
Hi @gjmvanboxtel , I'm drafting a conda-forge recipe here https://github.com/conda-forge/staged-recipes/pull/27475
and would like to invite you as the maintainer of the recipe. 

This recipe would allow people who use `conda` to install `gsignal` with `conda install -c conda-forge r-gsignal`.

If you are OK with me adding you to the recipe, please comment on the [PR](https://github.com/conda-forge/staged-recipes/pull/27475) with the following message before the **end of Wednesday** this week (US/East). 
  > I confirm that I would like to be added as the maintainer"

Once I finish the initial PR, you will then have the rights to edit the recipe in the future. The conda build process automatically tracks CRAN so it wouldn't take you any significant efforts once merged. (In most of the cases, the bot will automatically update and merge the changes without manual intervention.)

If you do not want me to list you as the maintainer, please let me know, or simply ignore this message. I will revise the maintainer list by the end of Wednesday (US/East).

Whether you want to be the maintainer or not, `conda-forge/r` and I will maintain the recipe. Since you are the maintainer of the original `gsignal`, you are always welcome to request to be the maintainer (so no rush).

**Comment by gjmvanboxtel** [comment]
Done
